conditions = {
            "Computer.T(0) and (not Computer.T(1)) and (not Computer.T(2)) and Computer.IEN and (Computer.FGO or Computer.FGI)": ["Computer.R = True"],
            "(not Computer.R) and Computer.T(0)": ["Computer.AR <<= Computer.PC"],
            "(not Computer.R) and Computer.T(1)": ["Computer.IR <<= Computer.Memory[Computer.decode(Computer.AR.data)]",
                                                   "Computer.PC.increment()"],
            "(not Computer.R) and Computer.T(2)": ["Computer.AR[0:12] = Computer.IR[0:12]",
                                                   "Computer.I = bool(Computer.IR[15])"],
            "(not Computer.D(7)) and Computer.I and Computer.T(3)": ["Computer.AR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.R and Computer.T(0)": ["Computer.AR.reset()", "Computer.TR <<= Computer.PC"],
            "Computer.R and Computer.T(1)": ["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.TR", "Computer.PC.reset()"],
            "Computer.R and Computer.T(2)": ["Computer.IEN = False", "Computer.PC.increment()", "Computer.R = False", "Computer.SC = 0"],
            "Computer.D(0) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(0) and Computer.T(5)": ["Computer.AC &= Computer.DR", "Computer.SC = 0"],
            "Computer.D(1) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(1) and Computer.T(5)": ["Computer.AC,Computer.E = Computer.AC + Computer.DR", "Computer.SC = 0"],
            "Computer.D(2) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(2) and Computer.T(5)": ["Computer.AC <<= Computer.DR", "Computer.SC = 0"],
            "Computer.D(3) and Computer.T(4)": ["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.AC", "Computer.SC = 0"],
            "Computer.D(4) and Computer.T(4)": ["Computer.PC <<= Computer.AR", "Computer.SC = 0"],
            "Computer.D(5) and Computer.T(4)": ["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.PC", "Computer.AR.increment()"],
            "Computer.D(5) and Computer.T(5)": ["Computer.PC <<= Computer.AR", "Computer.SC = 0"],
            "Computer.D(6) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(6) and Computer.T(5)": ["Computer.DR.increment()"],
            # "Computer.D(6) and Computer.T(6)":["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.DR","Computer.SC = 0","if (Computer.DR)"],
}