conditions = {
            "Computer.T(0) and (not Computer.T(1)) and (not Computer.T(2)) and Computer.IEN and (Computer.FGO or Computer.FGI)": ["Computer.R = True"],
            "Computer.D(7) and (not Computer.I) and Computer.T(3)":["Computer.r = True"],
            "Computer.D(7) and Computer.I and Computer.T(3)":["Computer.p = True"],
            "(not Computer.R) and Computer.T(0)": ["Computer.AR <<= Computer.PC"],
            "(not Computer.R) and Computer.T(1)": ["Computer.IR <<= Computer.Memory[Computer.decode(Computer.AR.data)]",
                                                   "Computer.PC.increment()"],
            "(not Computer.R) and Computer.T(2)": ["Computer.AR[0:12] = Computer.IR[0:12]",
                                                   "Computer.I = bool(Computer.IR[15])"],
            "(not Computer.D(7)) and Computer.I and Computer.T(3)": ["Computer.AR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.R and Computer.T(0)": ["Computer.AR.reset()", "Computer.TR <<= Computer.PC"],
            "Computer.R and Computer.T(1)": ["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.TR", "Computer.PC.reset()"],
            "Computer.R and Computer.T(2)": ["Computer.IEN = False", "Computer.PC.increment()", "Computer.R = False", "Computer.SC = 0"],
            "Computer.D(0) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(0) and Computer.T(5)": ["Computer.AC &= Computer.DR", "Computer.SC = 0"],
            "Computer.D(1) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(1) and Computer.T(5)": ["Computer.AC,Computer.E = Computer.AC + Computer.DR", "Computer.SC = 0"],
            "Computer.D(2) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(2) and Computer.T(5)": ["Computer.AC <<= Computer.DR", "Computer.SC = 0"],
            "Computer.D(3) and Computer.T(4)": ["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.AC", "Computer.SC = 0"],
            "Computer.D(4) and Computer.T(4)": ["Computer.PC <<= Computer.AR", "Computer.SC = 0"],
            "Computer.D(5) and Computer.T(4)": ["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.PC", "Computer.AR.increment()"],
            "Computer.D(5) and Computer.T(5)": ["Computer.PC <<= Computer.AR", "Computer.SC = 0"],
            "Computer.D(6) and Computer.T(4)": ["Computer.DR <<= Computer.Memory[Computer.decode(Computer.AR.data)]"],
            "Computer.D(6) and Computer.T(5)": ["Computer.DR.increment()"],
            "Computer.D(6) and Computer.T(6)": ["Computer.Memory[Computer.decode(Computer.AR.data)] <<= Computer.DR","Computer.SC = 0","if (int(Computer.DR)==0): Computer.PC.increment()"],
            "Computer.p or Computer.r":["Computer.SC = 0"],
            "Computer.r and Computer.IR[4]": ["Computer.AC.reset()"],
            "Computer.r and Computer.IR[5]": ["Computer.E = False"],
            "Computer.r and Computer.IR[6]": ["Computer.AC.complement()"],
            "Computer.r and Computer.IR[7]": ["Compuetr.E = not Computer.E"],
            "Computer.r and Computer.IR[8]": ["Computer.AC.shift_right()"],
            "Computer.r and Computer.IR[9]": ["Computer.AC.shift_left()"],
            "Computer.r and Computer.IR[10]": ["Computer.AC.increment()"],
            "Computer.r and Computer.IR[11]": ["if (int(Computer.AC)>0): Computer.PC.increment()"],
            "Computer.r and Computer.IR[12]": ["if (int(Computer.AC)<0): Computer.PC.increment()"],
            "Computer.r and Computer.IR[13]": ["if (int(Computer.AC)==0): Computer.PC.increment()"],
            "Computer.r and Computer.IR[14]": ["if (Computer.E==False): Computer.PC.increment()"],
            "Computer.r and Computer.IR[15]": ["Computer.S = False"],
            "Computer.p and Computer.IR[4]": ["Computer.AC.data[8:16] = Computer.INPR.data","Computer.FGI = False"],
            "Computer.p and Computer.IR[5]": ["Computer.OUTR.data = Computer.AC.data[8:16]","Computer.FGO = False"],
            "Computer.p and Computer.IR[6]": ["if (Computer.FGI): Computer.PC.increment()"],
            "Computer.p and Computer.IR[7]": ["if (Computer.FGO): Computer.PC.increment()"],
            "Computer.p and Computer.IR[8]": ["Computer.IEN = True"],
            "Computer.p and Computer.IR[9]": ["Computer.IEN = False"],
}